console.log("Hello World!")

console.log("Fav_website_Netflix")
console.log("Fav_website_Pottery_barn_online_catalog")
console.log("Fav_website_Creative_live")
console.log("Fav_game_Sims4")
console.log("Fav_game_Mario64")
console.log("Fav_game_CaesarIV")
console.log("Fav_artist_Laura_Berger")
console.log("Fav_artist_Lindsay_Adler")
console.log("Fav_artist_Von_Wong")
